# Generated by Django 4.1.7 on 2023-03-19 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "movie_type",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("drama", "Drama"),
                            ("family", "Family"),
                            ("animations", "Animations"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "my_rating",
                    models.IntegerField(
                        choices=[
                            (1, "One"),
                            (2, "Tow"),
                            (3, "Three"),
                            (4, "Four"),
                            (5, "Five"),
                        ],
                        default=0,
                    ),
                ),
                ("description", models.TextField(default="None")),
                ("year", models.DateField()),
                ("length", models.DurationField(default="1:00:00")),
                (
                    "image",
                    models.ImageField(
                        default="images/1.jpg", null=True, upload_to="images/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
