# Generated by Django 4.1.7 on 2023-03-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "movie_type",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("drama", "Drama"),
                            ("family", "Family"),
                            ("animations", "Animations"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "my_rating",
                    models.IntegerField(
                        choices=[
                            (1, "One"),
                            (2, "Tow"),
                            (3, "Three"),
                            (4, "Four"),
                            (5, "Five"),
                        ],
                        default=0,
                    ),
                ),
                ("year", models.DateTimeField()),
                ("length", models.TimeField()),
            ],
        ),
    ]
