# Generated by Django 4.1.7 on 2023-03-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="length",
            field=models.DurationField(default="1:00:00"),
        ),
    ]
