# Generated by Django 4.1.7 on 2023-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movie_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.DateField(),
        ),
    ]
