# Generated by Django 4.1.7 on 2023-03-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(default=None, null=True, upload_to="images/"),
        ),
    ]
