# Generated by Django 4.1.7 on 2023-03-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                default="images/1.jpg", null=True, upload_to="images/"
            ),
        ),
    ]
